name: AskTube AI CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Python syntax check
        run: |
          python -m compileall .

      - name: Import check
        env:
          SARVAM_API_KEY: "dummy"
          GOOGLE_API_KEY: "dummy"
        run: |
          python -c "import streamlit"
          python -c "import yt_dlp"
          python -c "import chromadb"
          python -c "import sarvamai"
          python -c "from google import genai"

      - name: Streamlit app check
        run: |
          python -m py_compile streamlit_app.py
